[package]
name = "bevy_cam_gizmo"
version = "0.1.0"
authors = ["Aevyrie Roessler <aevyrie@gmail.com> & Black Phlox <bphlox@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", version = "0.5", default-features = false }
bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking", branch = "master" }
bevy_mod_raycast = { git = "https://github.com/aevyrie/bevy_mod_raycast", branch = "master" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", version = "0.5", default-features = false, features = [
    "render",
    "bevy_wgpu",
    "bevy_winit",
    "bevy_gltf",
    "x11",
    "jpeg",
] }

